### ISSUE TITLE
Missing the ability to create a label from another label (context)

### ISSUE THREAD

**Issue by shadycuz** [cloudposse/terraform-terraform-label#19]
Your null label https://github.com/cloudposse/terraform-null-label module allows "context" to build powerful tagging strategies but this module is missing that feature. 

I tried using null-label module but it was missing a feature this label module had, I think it was to force lowercase. 

Kinda sucks to not have them be somewhat even in features since they are really similar. Will make this issue in case I want to PR a fix in the future.

**Comment by joriskoris-emburse** [comment]
Yes please

**Comment by Gowiem** [comment]
@shadycuz we're moving away from this module as terraform-null-label provides the same functionality and is actively maintained. See #29 for more details.
